//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_RSS_Migration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT_RSS_Migration.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drop table if exists ttrss_error_log;
        ///drop table if exists ttrss_plugin_storage;
        ///drop table if exists ttrss_linked_feeds;
        ///drop table if exists ttrss_linked_instances;
        ///drop table if exists ttrss_access_keys;
        ///drop table if exists ttrss_user_labels2;
        ///drop table if exists ttrss_labels2;
        ///drop table if exists ttrss_feedbrowser_cache;
        ///drop table if exists ttrss_version;
        ///drop table if exists ttrss_labels;
        ///drop table if exists ttrss_filters2_rules;
        ///drop table if exists ttrss_filters2_actions;
        ///drop table  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostgreSQL_Schema {
            get {
                return ResourceManager.GetString("PostgreSQL_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SEQUENCE {2}
        ///    START WITH 1
        ///    INCREMENT BY 1
        ///    NO MINVALUE
        ///    NO MAXVALUE
        ///    CACHE 1;
        ///ALTER TABLE public.{2} OWNER TO {4};
        ///ALTER SEQUENCE {2} OWNED BY {0}.{1};
        ///ALTER TABLE ONLY {0} ALTER COLUMN {1} SET DEFAULT nextval(&apos;{2}&apos;::regclass);
        ///ALTER SEQUENCE {2} RESTART WITH {3};.
        /// </summary>
        internal static string PostgreSQL_UpdateSeries {
            get {
                return ResourceManager.GetString("PostgreSQL_UpdateSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE SEQUENCE {2}
        ///    START WITH 1
        ///    INCREMENT BY 1
        ///    NO MINVALUE
        ///    NO MAXVALUE
        ///    CACHE 1;
        ///ALTER TABLE public.{2} OWNER TO {3};
        ///ALTER SEQUENCE {2} OWNED BY {0}.{1};
        ///ALTER TABLE ONLY {0} ALTER COLUMN {1} SET DEFAULT nextval(&apos;{2}&apos;::regclass);.
        /// </summary>
        internal static string PostgreSQL_UpdateSeries_Empty {
            get {
                return ResourceManager.GetString("PostgreSQL_UpdateSeries_Empty", resourceCulture);
            }
        }
    }
}
